server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    resolver ${NAMESERVER} valid=5s;

    location /api/ {
        set $backend "${BACKEND_URL}";
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /healthz {
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
